# Generated by Django 4.1.6 on 2023-02-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images/')),
                ('stock', models.IntegerField()),
                ('type', models.CharField(choices=[('Beauty', 'Beauty'), ('Electronic', 'Electronic'), ('CLothing', 'Clothing'), ('Shoes', 'Shoes'), ('Cars', 'Cars')], max_length=100)),
            ],
        ),
    ]
